### ISSUE TITLE
ControlDB Deployment Failure for Entra only authentication

### ISSUE THREAD

**Issue by bennyaustin** [bennyaustin/elt-framework#56]
### ControlDB-deployment.yml

Failed to add firewall rule. Unable to detect client IP Address. mssql: login error: Login failed for user '***'. Reason: Azure Active Directory only authentication is enabled. Please contact your system administrator.

**Comment by bennyaustin** [comment]
Fixed this issue in [fabric-accelerator](https://github.com/bennyaustin/fabric-accelerator) by actioning these steps:

- Disabled SQL Authentication on controlDB and enabled Entra only authentication as best practise and to comply with SFI
- Created a service principal and assigned _db_owner_ role to controlDB
- Updated the action deployment secret CONTROLDB_CONNECTIONSTRING to use a service principal authentication in this format
```
Server=<ASQL Server>.database.windows.net,1433;Authentication=Active Directory Service Principal; Encrypt=True;Database=controlDB;User Id=<Application(client) ID>;Password=<secret>
```

**Comment by CoulterJamesRDS** [comment]
@bennyaustin I still get this issue now after having pulled latest fork. 

<img width="1494" height="344" alt="Image" src="https://github.com/user-attachments/assets/c90718b6-3779-449a-9785-8acc952ce659" />
